function [WaveLengthExperiment_nm, Attenution_molar] = importExperimentData(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  [WAVELENGTHEXPERIMENT_NM, Attenuation molar] = IMPORTFILE(FILE) reads data
%  from the first worksheet in the Microsoft Excel spreadsheet file
%  named FILE.  Returns the data as column vectors.
%
%  [WAVELENGTHEXPERIMENT_NM, R_ESPERIMENT] = IMPORTFILE(FILE, SHEET)
%  reads from the specified worksheet.
%
%  [WAVELENGTHEXPERIMENT_NM, R_ESPERIMENT] = IMPORTFILE(FILE, SHEET,
%  DATALINES) reads from the specified worksheet for the specified row
%  interval(s). Specify DATALINES as a positive scalar integer or a
%  N-by-2 array of positive scalar integers for dis-contiguous row
%  intervals.
%
%  Example:
%  [WaveLengthExperiment_nm, R_esperiment] = importfile("G:\Min enhet\Studier\HT22\Projekt tillämpad fysik\Matlab\Experiment\QD_abs.xlsx", "Лист1", [2, 352]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Nov-2022 15:43:03

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 352];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":B" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["WaveLengthExperiment_nm", "Optical_density"];
opts.VariableTypes = ["double", "double"];

% Import the data
tbl = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":B" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    tbl = [tbl; tb]; %#ok<AGROW>
end

%% Convert to output type
WaveLengthExperiment_nm = tbl.WaveLengthExperiment_nm;
Attenution_molar = tbl.Optical_density;
end